baseURL: 'http://example.org/'
languageCode: en-us
title: My New Hugo Site
metaDataFormat: yaml
disableKinds:
  - taxonomy
  - taxonomyTerm
related:
  threshold: 80
  includeNewer: false
  toLower: false
  indices:
    - name: keywords
      weight: 150
    - name: author
      toLower: true
      weight: 30
    - name: tags
      weight: 100
    - name: date
      weight: 10
      pattern: '2006'
